### ISSUE TITLE
Bug: AttributeError: module 'crypten' has no attribute 'init'

### ISSUE THREAD

**Issue by Cloudmersive** [facebookresearch/CrypTen#108]
Followed installation instructions on Ubuntu 18.04 and received this error when running the example code from stable CryptTen release (latest pip):

```
$ python crypten.py
Traceback (most recent call last):
  File "crypten.py", line 2, in <module>
    import crypten
  File "/mnt/c/pytorch-classify/crypten.py", line 4, in <module>
    crypten.init()
AttributeError: module 'crypten' has no attribute 'init'
```

Example code:

```
import torch
import crypten

crypten.init()

x = torch.tensor([1.0, 2.0, 3.0])
x_enc = crypten.cryptensor(x) # encrypt

x_dec = x_enc.get_plain_text() # decrypt

y_enc = crypten.cryptensor([2.0, 3.0, 4.0])
sum_xy = x_enc + y_enc # add encrypted tensors
sum_xy_dec = sum_xy.get_plain_text() # decrypt sum
```

**Comment by Cloudmersive** [comment]
Resolved with reinstall
