### ISSUE TITLE
crypten.load reinitializing cuda in forked process?

### ISSUE THREAD

**Issue by SamuelDAdams** [facebookresearch/CrypTen#229]
I'm attempting to load a simple neural network on the master branch and receiving an error that CUDA is being reinitialized in a forked process when attempting to load from a checkpoint. Here's the stack trace:
```Process Process-1:
Traceback (most recent call last):
  File "/home/sam/miniconda3/envs/newcrypten/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/sam/miniconda3/envs/newcrypten/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sam/Documents/CrypTen/crypten/mpc/context.py", line 30, in _launch
    return_value = func(*func_args, **func_kwargs)
  File "/home/sam/Documents/svmvscnn/import.py", line 13, in run
    model = crypten.load('checkpoint.pth', dummy_model=model_class, src=0)
  File "/home/sam/Documents/CrypTen/crypten/__init__.py", line 337, in load
    obj = load_closure(f)
  File "/home/sam/miniconda3/envs/newcrypten/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/sam/miniconda3/envs/newcrypten/lib/python3.7/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/home/sam/miniconda3/envs/newcrypten/lib/python3.7/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/sam/miniconda3/envs/newcrypten/lib/python3.7/site-packages/torch/serialization.py", line 834, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/sam/miniconda3/envs/newcrypten/lib/python3.7/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/sam/miniconda3/envs/newcrypten/lib/python3.7/site-packages/torch/serialization.py", line 157, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/sam/miniconda3/envs/newcrypten/lib/python3.7/site-packages/torch/_utils.py", line 71, in _cuda
    with torch.cuda.device(device):
  File "/home/sam/miniconda3/envs/newcrypten/lib/python3.7/site-packages/torch/cuda/__init__.py", line 225, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
  File "/home/sam/miniconda3/envs/newcrypten/lib/python3.7/site-packages/torch/cuda/__init__.py", line 164, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

For reference, I'm running Ubuntu 20.04. Here is the code to reproduce. Both of the methods here fail. A checkpoint of the network will be attached to this issue.
```
import crypten
import crypten.mpc as mpc
import torch
from torch import nn
import torch.nn.functional as func

class Net1(nn.Module):
    def __init__(self):
        super(Net1, self).__init__()
        self.fc1 = nn.Linear(768, 10)
        self.fc2 = nn.Linear(10, 2)
    
    def forward(self, batch):
        x = self.fc1(batch)
        x = func.relu(x)
        x = self.fc2(x)
        return func.relu(x)

@mpc.run_multiprocess(world_size=2)
def run():
    model_class = Net1()
    #model = crypten.load_from_party('checkpoint.pth', model_class=model_class, src=0)
    model = crypten.load('checkpoint.pth', dummy_model=model_class, src=0)
    dummy_input = torch.empty((1, 1, 768))
    dummy_input.to('cuda')
    private_model = crypten.nn.from_pytorch(model, dummy_input)
    private_model.encrypt()
    private_model.eval()
    input = torch.rand((1, 1, 768))
    input = crypten.cryptensor(input, src=0)
    classification = private_model(input)
    print(classification)
    print('done')

crypten.init()
torch.set_num_threads(1)
run()
```
[checkpoint.zip](https://github.com/facebookresearch/CrypTen/files/6135851/checkpoint.zip)

**Comment by lvdmaaten** [comment]
How do you start the processes for the parties involved in the computation? If you do this via `multiprocessing`, it is important to note that [the CUDA runtime does not support the `fork` start method](https://pytorch.org/docs/stable/notes/multiprocessing.html#cuda-in-multiprocessing). This issue should go away if you [make sure `multiprocessing` uses the `spawn` method](https://github.com/facebookresearch/CrypTen/blob/master/examples/multiprocess_launcher.py#L22).
