### ISSUE TITLE
Updating weights of a CrypTen Deep Learning Model for a Federated Learning Architecture

### ISSUE THREAD

**Issue by anshpujara14** [facebookresearch/CrypTen#285]
Hi, I am trying to implement a Federated Learning architecture with privacy preserving model using CrypTen. 
Initially the weights are updated into the model using: `global_model.load_state_dict(global_weights)`

 Then I am encrypting the model using:
```
dummy_input = torch.empty(images.shape)
crypten_model = crypten.nn.from_pytorch(model, dummy_input)
crypten_model.encrypt()
global_model = crypten_model
```
Later when the Federated Averaging of weights is done, and when I try to update the weights of the model I am getting the following error:
```
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/src/federeated_mpc_main.py", line 116, in <module>
    crypten_model = crypten.nn.from_pytorch(global_model, dummy_input)
  File "/usr/local/lib/python3.7/dist-packages/crypten/nn/__init__.py", line 152, in from_pytorch
    output_names=["output"],
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 279, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 236, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/__init__.py", line 277, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/__init__.py", line 360, in forward
    self._force_outplace,
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/__init__.py", line 347, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/Colab Notebooks/src/models.py", line 37, in forward
    x = F.relu(F.max_pool2d(self.conv1(x), 2))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight 10 1 5 5, but got 3-dimensional input of size [60000, 28, 28] instead
  0% 0/10 [06:23<?, ?it/s]
```

### CNN Model architecture:
```
class CNNMnist(nn.Module):
    def __init__(self, args):
        super(CNNMnist, self).__init__()
        self.conv1 = nn.Conv2d(args.num_channels, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, args.num_classes)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, x.shape[1]*x.shape[2]*x.shape[3])
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)
```

Is there a way I can resolve this error and implement the Federated Learning architecture.

**Comment by lvdmaaten** [comment]
It appears you are trying to feed a 3D tensor into a model that requires a 4D input. This will result in an error in both PyTorch and CrypTen. Note that your input should be of size NxCxHxW -- your input is missing the channel dimension of size C.

If you perform an `unsqueeze(1)` on your input to make it a tensor of size `[60000, 1, 28, 28]`, your code should work correctly.

**Comment by anshpujara14** [comment]
Thank you, I'll try that.

**Comment by anshpujara14** [comment]
Hi @lvdmaaten 
I tried `unsqueeze(1)` on the input, and got the following error:
```
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/src/federeated_mpc_main.py", line 86, in <module>
    crypten_model = crypten.nn.from_pytorch(global_model, dummy_input)
  File "/usr/local/lib/python3.7/dist-packages/crypten/nn/__init__.py", line 171, in from_pytorch
    crypten_model = from_onnx(f)
  File "/usr/local/lib/python3.7/dist-packages/crypten/nn/__init__.py", line 208, in from_onnx
    raise ValueError("CrypTen does not support op %s." % node.op_type)
ValueError: CrypTen does not support op Mul.
  0% 0/10 [00:24<?, ?it/s]
```
