### ISSUE TITLE
PyTorch model convert to Crypten model  Failed !!!!

### ISSUE THREAD

**Issue by ZJG0** [facebookresearch/CrypTen#291]
Traceback (most recent call last):
  File "private_test.py", line 267, in <module>
    main()
  File "private_test.py", line 263, in main
    test(args, model)
  File "private_test.py", line 187, in test
    private_model = construct_private_model(input_size, model, args)
  File "private_test.py", line 177, in construct_private_model
    private_model = crypten.nn.from_pytorch(model_upd, dummy_input).encrypt(src=0)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py", line 45, in from_pytorch
    f = _from_pytorch_to_bytes(pytorch_model, dummy_input)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py", line 106, in _from_pytorch_to_bytes
    _export_pytorch_model(f, pytorch_model, dummy_input)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py", line 131, in _export_pytorch_model
    torch.onnx.export(pytorch_model, dummy_input, f, **kwargs)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/utils.py", line 487, in _model_to_graph
    torch._C._jit_pass_onnx_assign_output_shape(graph, output_tensors, out_desc, _onnx_shape_inference)
RuntimeError: ArrayRef: invalid index Index = 1; Length = 1

**Comment by knottb** [comment]
What model are you converting here? (Looks like a ViT model?) Appears that this is failing in the PyTorch onnx exporter. What version of PyTorch are you using?

**Comment by ZJG0** [comment]
Yes, this model is ViT(Vision Transformer). My version of PyTorch is 1.9.0. What can i do to solve it?

**Comment by ZJG0** [comment]
[model.txt](https://github.com/facebookresearch/CrypTen/files/6972376/model.txt)
This is the my model, i really don't konw how to debug further.

**Comment by ZJG0** [comment]
The cause of this issue is that `torch.onnx.export()` throws exceptions. I only use crypten to inference with private data, so how can i avoid this problem?

**Comment by knottb** [comment]
Yes, it seems that the `torch.onnx.export()` may have changed formatting. It is possible this would still work with PyTorch version 1.7.

However, there is another way to make this work. Rather than importing `import torch.nn as nn` you can replace with `import crypten.nn as nn`. I think all of the modules from your code are implemented in `crypten.nn`.

The one area of concern is loading your pre-trained model weights. This may be possible by using `load_state_dict`:

```
pytorch_model = load_pytorch_model()  # However you load the model
crypten_model = VisionTransformer(*args, **kwargs)  # However you'd like to initialize the model

crypten_model.load_state_dict(pytorch_model.state_dict())
crypten_model.encrypt()
```

Note that there may be some issues with parameter names. I can't debug this part without seeing how it ends up.

**Comment by ZJG0** [comment]
When i turn version of pytorch 1.9.0 to 1.7.0, there is a error as same as #294.
