### ISSUE TITLE
convert pytorch model to crypten model  failded

### ISSUE THREAD

**Issue by ZJG0** [facebookresearch/CrypTen#294]
### error info
Traceback (most recent call last):
  File "private_test.py", line 272, in <module>
    main()
  File "private_test.py", line 268, in main
    test(args, model)
  File "private_test.py", line 196, in test
    private_model = construct_private_model(input_size, model, args)
  File "private_test.py", line 186, in construct_private_model
    private_model = crypten.nn.from_pytorch(model_upd, dummy_input).encrypt(src=0)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py", line 45, in from_pytorch
    f = _from_pytorch_to_bytes(pytorch_model, dummy_input)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py", line 113, in _from_pytorch_to_bytes
    f = _export_pytorch_model(f, pytorch_model, dummy_input)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py", line 133, in _export_pytorch_model
    torch.onnx.export(pytorch_model, dummy_input, f, **kwargs)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/utils.py", line 718, in _export
    _check_onnx_proto(proto)
RuntimeError: Unrecognized attribute: ratio for operator Dropout
### debug
I think that the cause of this error is function `_update_onnx_symbolic_registry()`. However, i don't know how to fix it.

**Comment by ZJG0** [comment]
I added `nn.Dropout()` layer to the model `LetNet` of `crypten/example/mpc_cifar/mpc_cifar.py`, which appears the same error. So, this is a bug of `CrypTen`. How can i fix it?

**Comment by ZJG0** [comment]
1.9.0, which version is well?

**Comment by ZJG0** [comment]
Is there any progress?

**Comment by ZJG0** [comment]
https://github.com/facebookresearch/CrypTen/blob/7f432b2a259f0c8b26086272140bb0a5dcb56a51/crypten/nn/module.py#L1242-L1271
Class `Slice` does not support ONNX opset version 11, because `Slice` node does't have `attribute`  when ONNX opset version greater or equal to 10. However, when opset version less than 10, the onnx does't support dynamicSlice. So how to fix this problem?

**Comment by knottb** [comment]
This is a tricky issue that requires diving into the ONNX converter. This takes significant time to debug and is not a priority for us at the moment. You could try implementing the model using `crypten.nn.Module`s rather than converting using `from_pytorch()`.
