### ISSUE TITLE
ValueError: nn.Graph.forward() failed. Is graph unconnected?

### ISSUE THREAD

**Issue by ZJG0** [facebookresearch/CrypTen#301]
```
Traceback (most recent call last):
  File "private_test.py", line 277, in <module>
    main()
  File "private_test.py", line 273, in main
    test(args, model)
  File "private_test.py", line 202, in test
    valid(args, private_model, test_loader)
  File "private_test.py", line 114, in valid
    output = model(input)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/module.py", line 54, in __call__
    return self.forward(*args, **kwargs)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/module.py", line 536, in forward_function
    return object.__getattribute__(self, name)(*tuple(args), **kwargs)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/module.py", line 752, in forward
    raise ValueError("nn.Graph.forward() failed. Is graph unconnected?")
ValueError: nn.Graph.forward() failed. Is graph unconnected?
```

**Comment by lvdmaaten** [comment]
Can you share a code snippet that reproduces this error? 

The error indicates that all nodes that are connected to the inputs (either directly or indirectly) were evaluated, but that the output node was not among them. This suggests that the graph that was constructed consists of two or more disconnected components.

**Comment by ZJG0** [comment]
[repro.zip](https://github.com/facebookresearch/CrypTen/files/7077080/repro.zip)

**Comment by ZJG0** [comment]
If the cause of the error is as you said，how can I fix it?

**Comment by lvdmaaten** [comment]
I would have to dig in a bit to understand what is going wrong here. I have been able to successfully import a ViT into CrypTen before (adopted from timm) so it is certainly possible. The most likely issue is the name given to the model output by ONNX not matching what is expected, but I can only check that by running the code and doing some debugging during run-time.

Is [this repo](https://github.com/lucidrains/vit-pytorch) the dependency you are using? Are you installing CrypTen from source?

**Comment by ZJG0** [comment]
Yes, I used this repo and installed Crypten from source. 
> I have been able to successfully import a ViT into CrypTen before (adopted from timm) so it is certainly possible.

Are you offering a demo of forwording the ViT by Crypten? Thanks!
