### ISSUE TITLE
I got an error when I tried to run tutorial 4:Classification_with_Encrypted_Neural_Networks

### ISSUE THREAD

**Issue by Nada-Bu** [facebookresearch/CrypTen#322]
Code:
```
import crypten.mpc as mpc
import crypten.communicator as comm

labels = torch.load('/tmp/bob_test_labels.pth').long()
count = 100 # For illustration purposes, we'll use only 100 samples for classification

@mpc.run_multiprocess(world_size=2)
def encrypt_model_and_data():
    # Load pre-trained model to Alice
    model = crypten.load_from_party('models/tutorial4_alice_model.pth', src=ALICE)
    
    # Encrypt model from Alice 
    dummy_input = torch.empty((1, 784))
    private_model = crypten.nn.from_pytorch(model, dummy_input)
    private_model.encrypt(src=ALICE)
    
    # Load data to Bob
    data_enc = crypten.load_from_party('/tmp/bob_test.pth', src=BOB)
    data_enc2 = data_enc[:count]
    data_flatten = data_enc2.flatten(start_dim=1)

    # Classify the encrypted data
    private_model.eval()
    output_enc = private_model(data_flatten)
    
    # Compute the accuracy
    output = output_enc.get_plain_text()
    accuracy = compute_accuracy(output, labels[:count])
    crypten.print("\tAccuracy: {0:.4f}".format(accuracy.item()))
    
encrypt_model_and_data()
```

Error:
```
Process Process-2:
Process Process-1:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/crypten/mpc/context.py", line 29, in _launch
    crypten.init()
  File "/opt/conda/lib/python3.8/site-packages/crypten/__init__.py", line 77, in init
    _setup_prng()
  File "/opt/conda/lib/python3.8/site-packages/crypten/__init__.py", line 202, in _setup_prng
    generators[key][device] = torch.Generator(device=device)
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
  File "/opt/conda/lib/python3.8/site-packages/crypten/mpc/context.py", line 29, in _launch
    crypten.init()
  File "/opt/conda/lib/python3.8/site-packages/crypten/__init__.py", line 77, in init
    _setup_prng()
  File "/opt/conda/lib/python3.8/site-packages/crypten/__init__.py", line 202, in _setup_prng
    generators[key][device] = torch.Generator(device=device)
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
ERROR:root:One of the parties failed. Check past logs
```

**Comment by Nada-Bu** [comment]
Thanks for the help.
Yes, I have an AWS VM with CUDA-enabled. I have used VM to train many Deep NNs without any problem.

- !nvidia-smi ->
`NVIDIA-SMI 450.142.00   Driver Version: 450.142.00   CUDA Version: 11.4`

- torch.cuda.is_available() -> True
- 
I don't have any problem running tutorial one, but for any tutorial include `@mpc.run_multiprocess(world_size=2)`
I got the same error mentioned above.

For example I've tried tutorial 2, this part produces the same error about Cua "RuntimeError: CUDA error: initialization error":
`import crypten.mpc as mpc
import crypten.communicator as comm 
@mpc.run_multiprocess(world_size=2)
def examine_arithmetic_shares():
    x_enc = crypten.cryptensor([1, 2, 3], ptype=crypten.mpc.arithmetic)
    rank = comm.get().get_rank()
    crypten.print(f"\nRank {rank}:\n {x_enc}\n", in_order=True)
        
x = examine_arithmetic_shares()`

I will add an environment variable CUDA_LAUNCH_BLOCKING=1, then back with results.

thanks again
