### ISSUE TITLE
Run Crypten in multi machines more than 2

### ISSUE THREAD

**Issue by MinQinxy** [facebookresearch/CrypTen#339]
##  Question

It works well for the environment with 2 different machines by setting the $os.environ$'s value. But when the amont of different machines is increased to 3,  all of the process in 3 machines will block up unless I close the master node , which will close all process of  each node. My question is how can I build the distributed environment with 3 or more different machines.

## Detail

For node 1(10.0.0.51):
```python
custom_env = {
    "WORLD_SIZE":"3",
    "RANK":"0",
    "RENDEZVOUS":"tcp://10.0.0.51:9003",
    # "DISTRIBUTED_BACKEND":""
}
```
For node 2(10.0.0.52):
```python
custom_env = {
    "WORLD_SIZE":"3",
    "RANK":"1",
    "RENDEZVOUS":"tcp://10.0.0.51:9003",
    # "DISTRIBUTED_BACKEND":""
}
```
For node 3(10.0.0.50):
```python
custom_env = {
    "WORLD_SIZE":"3",
    "RANK":"2",
    "RENDEZVOUS":"tcp://10.0.0.51:9003",
    # "DISTRIBUTED_BACKEND":""
}
```
If the process in node 1 exits when ```crypten_init()```, other nodes will print :
```python
Traceback (most recent call last):
  File "/home/mindas/code/mpc2/main.py", line 20, in <module>
    crypten.init()
  File "/home/mindas/anaconda3/envs/flask/lib/python3.8/site-packages/crypten/__init__.py", line 69, in init
    comm._init(use_threads=False, init_ttp=crypten.mpc.ttp_required())
  File "/home/mindas/anaconda3/envs/flask/lib/python3.8/site-packages/crypten/communicator/__init__.py", line 32, in _init
    cls.initialize(rank, world_size, init_ttp=init_ttp)
  File "/home/mindas/anaconda3/envs/flask/lib/python3.8/site-packages/crypten/communicator/distributed_communicator.py", line 98, in initialize
    cls.instance = DistributedCommunicator(init_ttp=init_ttp)
  File "/home/mindas/anaconda3/envs/flask/lib/python3.8/site-packages/crypten/communicator/distributed_communicator.py", line 55, in __init__
    dist.init_process_group(
  File "/home/mindas/anaconda3/envs/flask/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 583, in init_process_group
    default_pg = _new_process_group_helper(
  File "/home/mindas/anaconda3/envs/flask/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 684, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, rank, world_size, timeout=timeout)
RuntimeError: Connection reset by peer
```
## Additional info
The code in node 1 is :
```python
import crypten
import torch
import os
import crypten.communicator as comm
torch.set_num_threads(1)

custom_env = {
    "WORLD_SIZE":"3",
    "RANK":"0",
    "RENDEZVOUS":"tcp://10.0.0.51:9003",
    # "DISTRIBUTED_BACKEND":""
}

for k,v in custom_env.items():
    os.environ[k] = v
print("before init")
crypten.init()
print("inited 1")
def run_code():
    print(comm.get().get_rank())
```
All three nodes  are ubuntu vms.

**Comment by wang10012** [comment]
You can try this configuration：
communicator_args = {
    "WORLD_SIZE": "3",
    "RANK": "0",  # 1, 2
    "RENDEZVOUS": "env://",
    "MASTER_ADDR": "10.0.0.51",
    "MASTER_PORT": "9003",
    "BACKEND": "gloo",
}

**Comment by MinQinxy** [comment]
> You can try this configuration：
> 
> ```
> communicator_args = {
>     "WORLD_SIZE": "3",
>     "RANK": "0",  # 1, 2
>     "RENDEZVOUS": "env://",
>     "MASTER_ADDR": "10.0.0.51",
>     "MASTER_PORT": "9003",
>     "BACKEND": "gloo",
> }
> ```


I just tried this configuration, but unfortunately, the same problem happened. And other type of `torch.distribute` like share file store  with args:
```python
communicator_args = {
     "WORLD_SIZE": "3",
    "RANK": "0",  # 1, 2
    "RENDEZVOUS": f"file:///tmp/mpc1_{str(uuid.uuid1())}",
    "MASTER_ADDR": "10.0.0.51",
    "MASTER_PORT": "9003",
    "BACKEND": "gloo",
}
```   
it performed the same result which  blocked up when `crypten.init()`

**Comment by TomHeaven** [comment]
Try my [demo](https://github.com/TomHeaven/crypten_cifar10_cuda_distributed/blob/main/mpc_cifar.py) to see if it works. @MinQinxy

**Comment by Ye-D** [comment]
Hi, have you fixed the problem? @MinQinxy
