### ISSUE TITLE
Code was hang when calling crypten.nn.from_pytorch

### ISSUE THREAD

**Issue by Flyingbeanss** [facebookresearch/CrypTen#378]
Hello. When I use the `crypten.nn.from_pytorch `,the code is hung and do not go to the next line.The code is here

```
import crypten.mpc as mpc
@mpc.run_multiprocess(world_size=2)
def run():
    model_plaintext=torch.load('resnet18_train_fashion_minist.pth',map_location=torch.device('cpu'))#
    # print(model_plaintext)
    dummy_input = torch.empty(100, 1, 32, 32)
    model = crypten.nn.from_pytorch(model_plaintext, dummy_input=dummy_input)
    model.encrypt(src=alice)
    model.eval()
```

After I see some similar problem in #88 ,I add `torch.set_num_threads(1)`.But I received this error message

```
Process Process-1:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/converters.py", line 28, in _A2B
    binary_tensor = binary_tensor.sum(dim=0)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/binary.py", line 354, in sum
    x = x0 + x1
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/binary.py", line 297, in add
    return circuit.add(self, y)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/circuit.py", line 127, in add
    S = x & y
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/binary.py", line 256, in __and__
    return result.__iand__(y)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/binary.py", line 241, in __iand__
    self.share.set_(beaver.AND(self, y).share.data)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/beaver.py", line 185, in AND
    eps_del = BinarySharedTensor.reveal_batch([x ^ a, y ^ b])
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/binary.py", line 382, in reveal_batch
    return comm.get().all_reduce(shares, op=op, batched=True)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/communicator/communicator.py", line 234, in logging_wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/communicator/distributed_communicator.py", line 203, in all_reduce
    req.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:26538

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/context.py", line 30, in _launch
    return_value = func(*func_args, **func_kwargs)
  File "/tmp/ipykernel_8639/2214762127.py", line 22, in run
    res.append(model(data[i]))
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/nn/module.py", line 50, in __call__
    return self.forward(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/nn/module.py", line 532, in forward_function
    return object.__getattribute__(self, name)(*tuple(args), **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/nn/module.py", line 714, in forward
    output = module(input)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/nn/module.py", line 50, in __call__
    return self.forward(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/nn/module.py", line 532, in forward_function
    return object.__getattribute__(self, name)(*tuple(args), **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/nn/module.py", line 2209, in forward
    return x.relu()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/cryptensor.py", line 342, in autograd_forward
    return self.__getattribute__(name)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/common/functions/logic.py", line 85, in relu
    return self * self.ge(0)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/common/functions/logic.py", line 35, in ge
    return 1 - self.lt(y)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/common/functions/logic.py", line 50, in lt
    return (self - y)._ltz()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/mpc.py", line 238, in _ltz
    result = self._to_ptype(Ptype.binary)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/mpc.py", line 149, in _to_ptype
    retval._tensor = convert(self._tensor, ptype, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/converters.py", line 78, in convert
    return _A2B(tensor)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/converters.py", line 35, in _A2B
    binary_tensor = binary_share if i == 0 else binary_tensor + binary_share
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/binary.py", line 297, in add
    return circuit.add(self, y)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/circuit.py", line 127, in add
    S = x & y
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/binary.py", line 256, in __and__
    return result.__iand__(y)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/binary.py", line 241, in __iand__
    self.share.set_(beaver.AND(self, y).share.data)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/beaver.py", line 185, in AND
    eps_del = BinarySharedTensor.reveal_batch([x ^ a, y ^ b])
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/mpc/primitives/binary.py", line 382, in reveal_batch
    return comm.get().all_reduce(shares, op=op, batched=True)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/communicator/communicator.py", line 234, in logging_wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/crypten/communicator/distributed_communicator.py", line 203, in all_reduce
    req.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:26538
ERROR:root:One of the parties failed. Check past logs
```

I can successfully run the code in the tutorial 5's code ,is there something wrong with my code? The tutorial's code is here.

```
import crypten.mpc as mpc
import crypten.communicator as comm

@mpc.run_multiprocess(world_size=2)
def forward_single_encrypted_layer():
    # Load and encrypt the layer
    layer = crypten.load_from_party(layer_linear_file, src=ALICE)
    layer_enc = crypten.nn.from_pytorch(layer, dummy_input=torch.empty((1,4)))
    layer_enc.encrypt(src=ALICE)
```

**Comment by Flyingbeanss** [comment]
And after I comment 
```
import crypten.mpc as mpc
@mpc.run_multiprocess(world_size=2)
```
The code will return to normal.

**Comment by pierrestock** [comment]
Hey Flyingbeanss, 

Thanks for your interest and congrats on auto-fixing your bug, can we close the issue?

Pierre

**Comment by Flyingbeanss** [comment]
Hi @pierrestock , sorry to bother you. I am a newbie about this. I will close this as your  wish.:)
