### ISSUE TITLE
module 'torch._C' has no attribute 'HalfStorageBase'

### ISSUE THREAD

**Issue by chauhang** [facebookresearch/CrypTen#389]
1. With the pip install crypten  - Running any of the Crypten examples with PT 1.12 throws following error: 

> Traceback (most recent call last):
  File "examples/tfe_benchmarks/launcher.py", line 26, in <module>
    from examples.multiprocess_launcher import MultiProcessLauncher
  File "/Users/gchauhan/opt/anaconda3/envs/ptn/lib/python3.8/site-packages/examples/__init__.py", line 9, in <module>
    from .multiprocess_launcher import MultiProcessLauncher
  File "/Users/gchauhan/opt/anaconda3/envs/ptn/lib/python3.8/site-packages/examples/multiprocess_launcher.py", line 13, in <module>
    import crypten
  File "/Users/gchauhan/opt/anaconda3/envs/ptn/lib/python3.8/site-packages/crypten/__init__.py", line 17, in <module>
    import crypten.communicator as comm
  File "/Users/gchauhan/opt/anaconda3/envs/ptn/lib/python3.8/site-packages/crypten/communicator/__init__.py", line 9, in <module>
    from .distributed_communicator import DistributedCommunicator
  File "/Users/gchauhan/opt/anaconda3/envs/ptn/lib/python3.8/site-packages/crypten/communicator/distributed_communicator.py", line 17, in <module>
    from crypten.common import serial
  File "/Users/gchauhan/opt/anaconda3/envs/ptn/lib/python3.8/site-packages/crypten/common/serial.py", line 59, in <module>
    class RestrictedUnpickler(pickle.Unpickler):
  File "/Users/gchauhan/opt/anaconda3/envs/ptn/lib/python3.8/site-packages/crypten/common/serial.py", line 96, in RestrictedUnpickler
    "torch._C.HalfStorageBase": torch._C.HalfStorageBase,
AttributeError: module 'torch._C' has no attribute 'HalfStorageBase'

2. On using install from source, CrypTen downgrades PyTorch version to 1.9

> Installing collected packages: torch, crypten
  Attempting uninstall: torch
    Found existing installation: torch 1.12.0
    Uninstalling torch-1.12.0:
      Successfully uninstalled torch-1.12.0
  Running setup.py develop for crypten

3. Install CrypTen from source, Uninstall the downgraded PyTorch and then reinstalling PyTorch 1.12, and run the examples finally works

It will help to fix the install steps so that PyTorch version does not get downgraded and/or publish the latest CrypTen pip packages

**Comment by lvdmaaten** [comment]
Do you observe this issue when you install CrypTen from source? I think this issue was fixed in https://github.com/facebookresearch/CrypTen/commit/5d8e52d05cd4c6ea36fc3eb32fa3f7c799e98662.

**Comment by chauhang** [comment]
@lvdmaaten Install from sources downgraded PyTorch to 1.9 and one has to reinstall PyTorch again after installing Crypten from source to work around this problem. I suggest either fixing the dependencies or updating the documentation to reflect this.

**Comment by lvdmaaten** [comment]
Oh interesting. I wonder what triggers the downgrade. CrypTen's `requirements.txt` [should be perfectly okay with PyTorch 1.12](https://github.com/facebookresearch/CrypTen/blob/main/requirements.txt#L1) so maybe it is one of the other dependencies triggering this?
