### ISSUE TITLE
NotImplementedError: CrypTen does not support torch function <method 'add' of 'torch._C._TensorBase' objects>.

### ISSUE THREAD

**Issue by ZJG0** [facebookresearch/CrypTen#403]
```
Traceback (most recent call last):
  File "inference.py", line 91, in <module>
    predict = private_model(enc_private_input, dec_private_input)
  File "/root/PPTF/crypten/nn/module.py", line 53, in __call__
    return self.forward(*args, **kwargs)
  File "/root/PPTF/crypten/nn/module.py", line 535, in forward_function
    return object.__getattribute__(self, name)(*tuple(args), **kwargs)
  File "/root/PPTF/crypten/nn/module.py", line 717, in forward
    output = module(input)
  File "/root/PPTF/crypten/nn/module.py", line 53, in __call__
    return self.forward(*args, **kwargs)
  File "/root/PPTF/crypten/nn/module.py", line 535, in forward_function
    return object.__getattribute__(self, name)(*tuple(args), **kwargs)
  File "/root/PPTF/crypten/nn/module.py", line 1484, in forward
    return crypten.where(condition, x1, x2)
  File "/root/PPTF/crypten/__init__.py", line 446, in where
    return input * condition + other * (1 - condition)
  File "/root/PPTF/crypten/cryptensor.py", line 300, in __torch_function__
    raise NotImplementedError(
NotImplementedError: CrypTen does not support torch function <method 'add' of 'torch._C._TensorBase' objects>.
```

**Comment by lvdmaaten** [comment]
Can you please provide a minimal repro so that I can try and reproduce this error?

**Comment by ZJG0** [comment]
@lvdmaaten 
#### Minimal Model Structure
```
class NN(nn.Sequential):
    # network architecture:
    def __init__(self, mask):
        super(NN, self).__init__()
        self.mask = mask
        self.fc = nn.Linear(3, 3)
    def forward(self, attn):
        masked = attn.masked_fill(self.mask == 0, 2.)
        result = self.fc(masked)
        return result
``` 
#### Main code
```
model = torch.load('testMask.pth')
crypten.init()
dummy_input = torch.randn(3, 3)
private_model = crypten.nn.from_pytorch(model, dummy_input).encrypt()
private_inputs = crypten.cryptensor(dummy_input)
private_model(private_inputs)
```
The saved model will be uploaded!
[testMask.pth.zip](https://github.com/facebookresearch/CrypTen/files/9507276/testMask.pth.zip)


> Can you please provide a minimal repro so that I can try and reproduce this error?

**Comment by ZJG0** [comment]
@lvdmaaten Any progress on this issue?

**Comment by lvdmaaten** [comment]
@ZJG0 I understand the issue now. Here is a much simpler repro of the same issue:
```python
import crypten
import torch

crypten.init()

result = torch.randn(3, 3) + crypten.cryptensor(torch.randn(3, 3))
```
What happens is that the `__add__` function of the PyTorch tensor gets called (which fails because it doesn't know how to deal with `CrypTensor`s) as a result of which the code never gets to calling `CrypTensor.__radd__`. I am trying to understand whether this issue was always there and we just never noticed, or whether it is due to recent changes in PyTorch.

**Comment by ankitkumarpali** [comment]
I am facing similar issue with "matmul" function.
Error is: NotImplementedError: CrypTen does not support torch function <method 'matmul' of 'torch._C._TensorBase' objects>
