### ISSUE TITLE
AssertionError: input needs to be a list or tuple

### ISSUE THREAD

**Issue by dikjstra** [facebookresearch/CrypTen#427]
The error occurs when I run the code below：
```python
import os

import numpy as np
import torch
import crypten
import torch.nn as nn

from torchvision import models, transforms
from PIL import Image
from torch.autograd import Variable

crypten.init()

inf_model = models.densenet121(pretrained=False)
num_ftrs = inf_model.classifier.in_features # Get the number of features output from CNN layer
inf_model.classifier = nn.Linear(num_ftrs, 2)
inf_model.to(torch.device('cpu'))
inf_model.load_state_dict(torch.load('./best_model.pth', map_location='cpu'))

dummy_input = torch.empty(1, 3, 150, 150)
model = crypten.nn.from_pytorch(inf_model, dummy_input)
model.encrypt()
model.eval()

mean_nums = [0.485, 0.456, 0.406]
std_nums = [0.229, 0.224, 0.225]

test_transforms = transforms.Compose([
                                      transforms.Resize((150,150)),
                                      transforms.ToTensor(),
                                      transforms.Normalize(mean=mean_nums, std=std_nums)
])

img_path = 'COVID19-DATASET/test/covid19/COVID-19(219).png'
DATA_PATH = 'COVID19-DATASET/train'

class_names = os.listdir(DATA_PATH)

image = Image.open(img_path)
image_tensor = test_transforms(image)
input = image_tensor.unsqueeze_(0)
input = Variable(input)
print(input.shape)

input = input.to(torch.device('cpu'))
input_enc = crypten.cryptensor(input)

print(model)
print(input_enc.shape)

out_enc = model(input_enc)
out = out_enc.get_plain_text()
_, preds = torch.max(out, 1)
idx = preds.cpu().numpy()[0]
pred_class = class_names[idx]
score = out[0][0].item()

print("Predicted: {}".format(pred_class))
```
Source of error: **out_enc = model(input_enc)**

console display：
```python
/home/stu01/.conda/envs/mycf/bin/python3.7 /home/stu01/projects/torch_projects/test07/COVID_19_Detection_crypten_test.py 
/home/stu01/mycrypten/CrypTen/crypten/nn/onnx_converter.py:164: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:143.)
  param = torch.from_numpy(numpy_helper.to_array(node))
torch.Size([1, 3, 150, 150])
Graph encrypted module
torch.Size([1, 3, 150, 150])
Traceback (most recent call last):
  File "/home/stu01/projects/torch_projects/test07/COVID_19_Detection_crypten_test.py", line 51, in <module>
    out_enc = model(input_enc)
  File "/home/stu01/mycrypten/CrypTen/crypten/nn/module.py", line 48, in __call__
    return self.forward(*args, **kwargs)
  File "/home/stu01/mycrypten/CrypTen/crypten/nn/module.py", line 530, in forward_function
    return object.__getattribute__(self, name)(*tuple(args), **kwargs)
  File "/home/stu01/mycrypten/CrypTen/crypten/nn/module.py", line 712, in forward
    output = module(input)
  File "/home/stu01/mycrypten/CrypTen/crypten/nn/module.py", line 48, in __call__
    return self.forward(*args, **kwargs)
  File "/home/stu01/mycrypten/CrypTen/crypten/nn/module.py", line 530, in forward_function
    return object.__getattribute__(self, name)(*tuple(args), **kwargs)
  File "/home/stu01/mycrypten/CrypTen/crypten/nn/module.py", line 1517, in forward
    assert isinstance(input, (list, tuple)), "input needs to be a list or tuple"
AssertionError: input needs to be a list or tuple

Process finished with exit code 1
```

**Comment by lvdmaaten** [comment]
I suspect this has to do with one of the many changes in ONNX since we developed the ONNX importer. I tried to fix some of these in https://github.com/facebookresearch/CrypTen/pull/396/files but I didn't get to covering them all -- it is almost impossible to keep up with all the changes that ONNX is making in between versions. 

You can try and fix these locally by looking at what `input` actually looks like in `module.py:1517` and adapt the implementation of the `Concat` module accordingly. It may take us some time to develop a more permanent solution though -- I think we need to migrate off of ONNX but there isn't a good alternative as far as I can tell.
