### ISSUE TITLE
module 'torch._C' has no attribute 'HalfStorageBase'

### ISSUE THREAD

**Issue by Wangxinqian** [facebookresearch/CrypTen#434]
`>>> import crypten
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xinqianwang/opt/anaconda3/envs/crypten_env/lib/python3.7/site-packages/crypten/__init__.py", line 17, in <module>
    import crypten.communicator as comm
  File "/Users/xinqianwang/opt/anaconda3/envs/crypten_env/lib/python3.7/site-packages/crypten/communicator/__init__.py", line 9, in <module>
    from .distributed_communicator import DistributedCommunicator
  File "/Users/xinqianwang/opt/anaconda3/envs/crypten_env/lib/python3.7/site-packages/crypten/communicator/distributed_communicator.py", line 17, in <module>
    from crypten.common import serial
  File "/Users/xinqianwang/opt/anaconda3/envs/crypten_env/lib/python3.7/site-packages/crypten/common/serial.py", line 59, in <module>
    class RestrictedUnpickler(pickle.Unpickler):
  File "/Users/xinqianwang/opt/anaconda3/envs/crypten_env/lib/python3.7/site-packages/crypten/common/serial.py", line 96, in RestrictedUnpickler
    "torch._C.HalfStorageBase": torch._C.HalfStorageBase,
AttributeError: module 'torch._C' has no attribute 'HalfStorageBase'
`
I successfully install all the requirements, but it turns out this...

**Comment by lvdmaaten** [comment]
See https://github.com/facebookresearch/CrypTen/issues/391. Does installing CrypTen from source fix the issue for you?

**Comment by Wangxinqian** [comment]
Thanks, it works now after install tbe CrypTen from source.
