### ISSUE TITLE
Tutorial 4 - ValueError: CrypTen does not support ONNX op Identity.

### ISSUE THREAD

**Issue by ngkuru** [facebookresearch/CrypTen#455]
Hi, I am receiving a `ValueError: CrypTen does not support ONNX op Identity.` when trying to run tutorial 4's "Classifying Encrypted Data with Encrypted Model" section. I haven't made any changes to the code except adding a `%env CUDA_VISIBLE_DEVICES=""` to bypass CUDA initialization error. How do I get around this? Thank you

Log is below.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ngkuru/crypten/crypten/mpc/context.py", line 30, in _launch
    return_value = func(*func_args, **func_kwargs)
  File "/tmp/ipykernel_27669/2664848552.py", line 14, in encrypt_model_and_data
    private_model = crypten.nn.from_pytorch(model, dummy_input)
  File "/home/ngkuru/crypten/crypten/nn/onnx_converter.py", line 58, in from_pytorch
    crypten_model = from_onnx(f)
  File "/home/ngkuru/crypten/crypten/nn/onnx_converter.py", line 47, in from_onnx
    return _to_crypten(onnx_model)
  File "/home/ngkuru/crypten/crypten/nn/onnx_converter.py", line 184, in _to_crypten
    crypten_class = _get_operator_class(node.op_type, attributes)
  File "/home/ngkuru/crypten/crypten/nn/onnx_converter.py", line 260, in _get_operator_class
    raise ValueError(f"CrypTen does not support ONNX op {node_op_type}.")
ValueError: CrypTen does not support ONNX op Identity.
```

**Comment by jtfields** [comment]
I am receiving the same error when running Tutorial 4 on Google Colab - "ValueError: CrypTen does not support ONNX op Identity."

To run Crypten on Python 3.10, I downgraded the following - !pip install torch>=1.7.0 torchvision>=0.9.1 omegaconf>=2.0.6 onnx>=1.7.0 pandas>=1.2.2 pyyaml>=5.3.1 tensorboard future scipy>=1.6.0

**Comment by Adongua** [comment]
**Run Crypten on Python 3.9**
requirements.txt:
torch == 1.8.1
torchvision == 0.9.1
omegaconf == 2.0.6
onnx == 1.10.0
pandas == 1.2.2
pyyaml == 5.3.1
tensorboard
future
scipy == 1.6.0
sklearn
crypten
numpy == 1.19.5
`pip install -r  requirements.txt`
Afterwards,in the nn/onnx_converter.py of imported crypten,I converted `_OPSET_VERSION = 17` to `_OPSET_VERSION = 11`,and
this problem has been resolved.

**Comment by meitianyu** [comment]
> **Run Crypten on Python 3.9** requirements.txt: torch == 1.8.1 torchvision == 0.9.1 omegaconf == 2.0.6 onnx == 1.10.0 pandas == 1.2.2 pyyaml == 5.3.1 tensorboard future scipy == 1.6.0 sklearn crypten numpy == 1.19.5 `pip install -r requirements.txt` Afterwards,in the nn/onnx_converter.py of imported crypten,I converted `_OPSET_VERSION = 17` to `_OPSET_VERSION = 11`,and this problem has been resolved.

Hi I also encountered the same problem and tried to solve it the way you did, but it still didn't work. Are there any other special operations?

I have installed the following packages in python3.9:
torch==1.8.1
torchvision==0.9.1
omegaconf==2.0.6
onnx==1.10.0
pandas == 1.2.2
pyyaml==5.3.1
tensorboard
future
scipy==1.6.0
sklearn
cryptic
numpy==1.19.5
and changed the value of _OPSET_VERSION to 11, but the output is still ValueError: Unsupported ONNX opset version: 17

**Comment by IshanAryendu** [comment]
Use this command inside your project directory to apply the changes: `python3 setup.py install`

**Comment by 20184390301** [comment]
Hi,have you solved this problem now?
