### ISSUE TITLE
Support for python 3.8

### ISSUE THREAD

**Issue by labm1997** [facebookresearch/CrypTen#463]
##  Feature

It would be nice to have CrypTen working on Python >= 3.8, so that it wouldn't need Rosetta on Apple Silicon computers.

## Alternatives

  It's possible to use Python 3.7 with Rosetta, but with some performance drawbacks

## Additional context

Currently, Picke fails during serialization when using CrypTen on Python >= 3.8:
```
Traceback (most recent call last):
  File "/path/to/my/file.py", line 14, in <module>
    x = examine_arithmetic_shares()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luiz/Library/Python/3.11/lib/python/site-packages/crypten/mpc/context.py", line 94, in wrapper
    process.start()
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function examine_arithmetic_shares at 0x156aad9e0>: it's not the same object as __main__.examine_arithmetic_shares
```

Of course, there may be many other reasons not to support python 3.8.

**Comment by lvdmaaten** [comment]
Interesting. You are not seeing this error on Python 3.7? I wonder what changed. The error message suggests there is a code pattern [like this](https://stackoverflow.com/questions/1412787/picklingerror-cant-pickle-class-decimal-decimal-its-not-the-same-object/53869959#53869959), perhaps created by one of the `@wraps`(?). I wonder what changed in the behavior of `@wraps` in Python 3.8 though.
