### ISSUE TITLE
Should Crypten work with batched inference?

### ISSUE THREAD

**Issue by kwmaeng91** [facebookresearch/CrypTen#476]
Dear experts.
I can run Crypten fine with single samples, but when I try batched execution (even with batch size = 2) it fails with the following error:
As the reference example [here](https://github.com/facebookresearch/CrypTen/blob/6ef151101668591bcfb2bbf7e7ebd39ab6db0413/examples/mpc_imagenet/mpc_imagenet.py#L79) also uses single samples for inference, I wonder if batched inference is simply not supported or if this is a problem with my setup.
Specifically, I am running CIFAR10 + ResNet-18, and the error happens at the first ReLU layer when the two parties need to communicate (I am using a two-party setup).

```
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at ../third_party/gloo/gloo/transport/tcp/pair.cc:510] op.preamble.length <= op.nbytes. 262144 vs 40
Process Process-2:
Traceback (most recent call last):
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/converters.py", line 28, in _A2B
    binary_tensor = binary_tensor.sum(dim=0)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/binary.py", line 354, in sum
    x = x0 + x1
        ~~~^~~~
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/binary.py", line 297, in add
    return circuit.add(self, y)
           ^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/circuit.py", line 127, in add
    S = x & y
        ~~^~~
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/binary.py", line 256, in __and__
    return result.__iand__(y)
           ^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/binary.py", line 241, in __iand__
    self.share.set_(beaver.AND(self, y).share.data)
                    ^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/beaver.py", line 186, in AND
    eps_del = BinarySharedTensor.reveal_batch([x ^ a, y ^ b])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/binary.py", line 382, in reveal_batch
    return comm.get().all_reduce(shares, op=op, batched=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/communicator/communicator.py", line 234, in logging_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/communicator/distributed_communicator.py", line 202, in all_reduce
    req.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:589] Read error [146.186.150.13]:28593: Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/storage/work/kvm6242/RecSys_MPC/crypten_perf_vision.py", line 70, in run_process
    run_process_fn(args, rank, world_size)
  File "/storage/work/kvm6242/RecSys_MPC/crypten_perf_vision.py", line 191, in run_mpc
    y_enc = model_enc(x_enc)
            ^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/nn/module.py", line 54, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/nn/module.py", line 538, in forward_function
    return object.__getattribute__(self, name)(*tuple(args), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/nn/module.py", line 729, in forward
    output = module(input)
             ^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/nn/module.py", line 54, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/nn/module.py", line 538, in forward_function
    return object.__getattribute__(self, name)(*tuple(args), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/nn/module.py", line 2349, in forward
    return x.relu()
           ^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/cryptensor.py", line 340, in autograd_forward
    return self.__getattribute__(name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/common/functions/logic.py", line 85, in relu
    return self * self.ge(0)
                  ^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/common/functions/logic.py", line 35, in ge
    return 1 - self.lt(y)
               ^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/common/functions/logic.py", line 50, in lt
    return (self - y)._ltz()
           ^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/mpc.py", line 279, in _ltz
    result = self._to_ptype(Ptype.binary)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/mpc.py", line 155, in _to_ptype
    retval._tensor = convert(self._tensor, ptype, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/converters.py", line 78, in convert
    return _A2B(tensor)
           ^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/converters.py", line 35, in _A2B
  binary_tensor = binary_share if i == 0 else binary_tensor + binary_share
                                                ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/binary.py", line 297, in add
    return circuit.add(self, y)
           ^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/circuit.py", line 127, in add
    S = x & y
        ~~^~~
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/binary.py", line 256, in __and__
    return result.__iand__(y)
           ^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/binary.py", line 241, in __iand__
    self.share.set_(beaver.AND(self, y).share.data)
                    ^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/beaver.py", line 186, in AND
    eps_del = BinarySharedTensor.reveal_batch([x ^ a, y ^ b])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/mpc/primitives/binary.py", line 382, in reveal_batch
    return comm.get().all_reduce(shares, op=op, batched=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/communicator/communicator.py", line 234, in logging_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/kvm6242/work/.conda/envs/recsys_mpc/lib/python3.11/site-packages/crypten/communicator/distributed_communicator.py", line 202, in all_reduce
    req.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:589] Read error [146.186.150.13]:28593: Connection reset by peer
```

I think the main error is `op.preamble.length <= op.nbytes. 262144 vs 40`, but not sure what it is supposed to be meaning.
If anyone can give any insight, that would be great!

Thank you.

**Comment by kwmaeng91** [comment]
Actually, found that the issue was not about batching and something else. I was only calculating the loss from one of the rank, and for some reason that was the problem.
