### ISSUE TITLE
Tutorial 7 doesn't run because of AutogradCryptensor

### ISSUE THREAD

**Issue by youben11** [facebookresearch/CrypTen#97]
Current version of crypten doesn't allow to use AutogradCryptensor directly, but instead, suggest to use the requires_grad parameters with cryptensor constructor, so I updated Tutorial 7 as a way to test this new functionality, but cell 8 throws an error

```bash
/home/youben/anaconda3/envs/om-dev-nightly/lib/python3.7/site-packages/torch/storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
/home/youben/anaconda3/envs/om-dev-nightly/lib/python3.7/site-packages/torch/storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
Epoch 0 in progress:
Process Process-3:
Traceback (most recent call last):
  File "/home/youben/anaconda3/envs/om-dev-nightly/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/youben/anaconda3/envs/om-dev-nightly/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/mpc/context.py", line 30, in _launch
    return_value = func(*func_args, **func_kwargs)
  File "<stdin>", line 35, in run_encrypted_training
  File "/home/youben/git-repo/CrypTen/crypten/nn/module.py", line 42, in __call__
    return self.forward(*args, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/nn/module.py", line 373, in forward_function
    return object.__getattribute__(self, name)(*tuple(args), **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/nn/module.py", line 494, in forward
    output = self._modules[node_to_compute](input)
  File "/home/youben/git-repo/CrypTen/crypten/nn/module.py", line 42, in __call__
    return self.forward(*args, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/nn/module.py", line 373, in forward_function
    return object.__getattribute__(self, name)(*tuple(args), **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/nn/module.py", line 1453, in forward
    x = x.conv2d(self.weight, stride=self.stride, padding=self.padding)
  File "/home/youben/git-repo/CrypTen/crypten/cryptensor.py", line 261, in autograd_forward
    result = grad_fn.forward(ctx, *args, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/gradients.py", line 1358, in forward
    return input.conv2d(kernel, padding=padding, stride=stride)
  File "/home/youben/git-repo/CrypTen/crypten/mpc/mpc.py", line 41, in convert_wrapper
    return func(result, *args, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/mpc/mpc.py", line 1230, in ob_wrapper_function
    result._tensor = getattr(result._tensor, name)(value, *args, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/mpc/primitives/arithmetic.py", line 416, in conv2d
    return self._arithmetic_function(kernel, "conv2d", **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/mpc/primitives/arithmetic.py", line 254, in _arithmetic_function
    result, y, *args, **kwargs
  File "/home/youben/git-repo/CrypTen/crypten/mpc/primitives/beaver.py", line 62, in conv2d
    return __beaver_protocol("conv2d", x, y, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/mpc/primitives/beaver.py", line 37, in __beaver_protocol
    eps_del = ArithmeticSharedTensor.reveal_batch([x - a, y - b])
  File "/home/youben/git-repo/CrypTen/crypten/mpc/primitives/arithmetic.py", line 190, in reveal_batch
    return comm.get().all_reduce(shares, batched=True)
  File "/home/youben/git-repo/CrypTen/crypten/communicator/communicator.py", line 160, in logging_wrapper
    return func(self, *args, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/communicator/distributed_communicator.py", line 181, in all_reduce
    dist.all_reduce(tensor, op=op, group=self.main_group, async_op=True)
  File "/home/youben/anaconda3/envs/om-dev-nightly/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 919, in all_reduce
    _check_single_tensor(tensor, "tensor")
  File "/home/youben/anaconda3/envs/om-dev-nightly/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 233, in _check_single_tensor
    "to be of type torch.Tensor.".format(param_name))
RuntimeError: Invalid function argument. Expected parameter `tensor` to be of type torch.Tensor.
Process Process-4:
Traceback (most recent call last):
  File "/home/youben/anaconda3/envs/om-dev-nightly/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/youben/anaconda3/envs/om-dev-nightly/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/mpc/context.py", line 30, in _launch
    return_value = func(*func_args, **func_kwargs)
  File "<stdin>", line 35, in run_encrypted_training
  File "/home/youben/git-repo/CrypTen/crypten/nn/module.py", line 42, in __call__
    return self.forward(*args, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/nn/module.py", line 373, in forward_function
    return object.__getattribute__(self, name)(*tuple(args), **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/nn/module.py", line 494, in forward
    output = self._modules[node_to_compute](input)
  File "/home/youben/git-repo/CrypTen/crypten/nn/module.py", line 42, in __call__
    return self.forward(*args, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/nn/module.py", line 373, in forward_function
    return object.__getattribute__(self, name)(*tuple(args), **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/nn/module.py", line 1453, in forward
    x = x.conv2d(self.weight, stride=self.stride, padding=self.padding)
  File "/home/youben/git-repo/CrypTen/crypten/cryptensor.py", line 261, in autograd_forward
    result = grad_fn.forward(ctx, *args, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/gradients.py", line 1358, in forward
    return input.conv2d(kernel, padding=padding, stride=stride)
  File "/home/youben/git-repo/CrypTen/crypten/mpc/mpc.py", line 41, in convert_wrapper
    return func(result, *args, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/mpc/mpc.py", line 1230, in ob_wrapper_function
    result._tensor = getattr(result._tensor, name)(value, *args, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/mpc/primitives/arithmetic.py", line 416, in conv2d
    return self._arithmetic_function(kernel, "conv2d", **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/mpc/primitives/arithmetic.py", line 254, in _arithmetic_function
    result, y, *args, **kwargs
  File "/home/youben/git-repo/CrypTen/crypten/mpc/primitives/beaver.py", line 62, in conv2d
    return __beaver_protocol("conv2d", x, y, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/mpc/primitives/beaver.py", line 37, in __beaver_protocol
    eps_del = ArithmeticSharedTensor.reveal_batch([x - a, y - b])
  File "/home/youben/git-repo/CrypTen/crypten/mpc/primitives/arithmetic.py", line 190, in reveal_batch
    return comm.get().all_reduce(shares, batched=True)
  File "/home/youben/git-repo/CrypTen/crypten/communicator/communicator.py", line 160, in logging_wrapper
    return func(self, *args, **kwargs)
  File "/home/youben/git-repo/CrypTen/crypten/communicator/distributed_communicator.py", line 184, in all_reduce
    req.wait()
RuntimeError: [/opt/conda/conda-bld/pytorch_1585984172566/work/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [127.0.1.1]:23453
ERROR:root:One of the parties failed. Check past logs
```

**Comment by jspisak** [comment]
@vreis - can you take a look at this?

**Comment by shubho** [comment]
Probably for @vshobha

**Comment by knottb** [comment]
I'll take a look as well.

**Comment by knottb** [comment]
This should have been fixed by https://github.com/facebookresearch/CrypTen/commit/2ac4d9bf3d03a6cc2ace758c44eed9adf1a60a0f

Closing this out. If issues persist, re-open the task or let me know.
